# Generated by Django 3.2 on 2023-05-13 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_alter_orderrecord_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderrecord',
            old_name='mobile_number',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='orderrecord',
            name='home_number',
        ),
    ]
