# Generated by Django 3.2 on 2023-06-22 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_auto_20230513_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderrecord',
            name='house_name',
        ),
    ]
