# Generated by Django 3.2 on 2023-06-22 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_orderrecord_house_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderrecord',
            name='house_name',
        ),
    ]
