# Generated by Django 3.2 on 2023-06-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_alter_orderrecord_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrecord',
            name='email',
            field=models.EmailField(max_length=300),
        ),
    ]
