# Generated by Django 3.2 on 2023-05-13 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_home_number',
            new_name='default_phone_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='default_mobile_number',
        ),
    ]
