# Generated by Django 3.2 on 2023-06-22 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20230513_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='default_house_name',
        ),
    ]
